# Generated by Django 4.0.2 on 2022-03-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicealbum',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование услуги'),
        ),
        migrations.AlterField(
            model_name='servicealbum',
            name='priceBarber',
            field=models.IntegerField(verbose_name='Цена барбера'),
        ),
        migrations.AlterField(
            model_name='servicealbum',
            name='priceBigBarber',
            field=models.IntegerField(verbose_name='Цена старшего барбера'),
        ),
        migrations.AlterField(
            model_name='servicealbum',
            name='priceTopBarber',
            field=models.IntegerField(verbose_name='Цена ТОП барбера'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='offer',
            field=models.CharField(max_length=200, verbose_name='Cпециальное предложение'),
        ),
    ]
