# Generated by Django 3.1.4 on 2022-03-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220317_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Аватарка')),
                ('firstName', models.CharField(max_length=30, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalaryHairstyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galary', to='mainapp.barber', verbose_name='Барбер')),
            ],
        ),
    ]
