# Generated by Django 3.1.4 on 2022-03-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_barber_galaryhairstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaryhairstyle',
            name='chek',
            field=models.BooleanField(default=False),
        ),
    ]
