# Generated by Django 3.1.4 on 2022-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_galaryhairstyle_chek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('data', models.DateField(verbose_name='Дата')),
                ('starts', models.IntegerField(verbose_name='Колличество звезд')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
