# Generated by Django 3.1.4 on 2022-04-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.CharField(max_length=10, verbose_name='Дата'),
        ),
    ]
